### PR TITLE
add foot-extra

### PR DESCRIPTION
**Pull request by p00f**
https://aur.archlinux.org/packages/foot-terminfo/#pinned-834657 ncurses now has a basic terminfo for foot, and there is another terminfo package which includes non-standard capabilities of foot. This PR adds that

### CODE REVIEW

**Comment by dnkl** [comment]
Ncurses has both `foot` and `foot-direct`. And then there's `foot-extra` and `foot-extra-direct`. There may be other, distro-specific, variants of `foot-extra` as well.

As such, it's probably better to match against `foot*`...

**Comment by p00f** [comment]
Done

**Comment by dnkl** [comment]
Depends on what the required caps are ;)

The difference between `-direct` and the regular version is that `-direct` announces true-color support (but in a way that actually **breaks** most applications - emacs is the only one I know that knows how to use it).

The `-extra` variants add a couple of extra, non-standard capabilities, mainly used by tmux.

**Comment by dnkl** [comment]
(note: you can run e.g. `infocmp -x foot foot-direct` to compare two terminfos)

**Comment by p00f** [comment]
Thanks

**Comment by lunaryorn** [comment]
So what's the outcome?  Is the code in this merge request as desired now?

If so the changelog doesn't seem up to date, and the manpage needs to be updated as well 🙂

**Comment by p00f** [comment]
> If so the changelog doesn't seem up to date, and the manpage needs to be updated as well slightly_smiling_face
Will do

**Comment by p00f** [comment]
@lunaryorn done!

**Pull request merged**
